version: v1.0
name: Hercules
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Setup
    dependencies: []
    task:
      jobs:
        - name: bundle
          commands:
            - checkout
            - sem-version ruby 3.0.1
            - bundle install
  - name: Unit tests
    dependencies:
      - Setup
    task:
      prologue:
        commands:
          - sem-version ruby 3.0.1
          - checkout
          - cache restore
          - bundle install
          - cache store
      jobs:
        - name: RSpec
          commands:
            - bundle exec rspec spec
